[versions]
java = "VERSION_17"
minSdk = "26"
securityCrypto = "1.0.0"
targetSdk = "34"
compileSdk = "34"
versionCode = "1"
versionName = "1.0"


agp = "8.3.2"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
detekt = "1.23.3"

appcompat = "1.6.1"
glide = "4.16.0"
constraintlayout = "2.1.4"
coreKtx = "1.9.0"
dagger = "2.50"
fragmentKtx = "1.6.2"
espressoCore = "3.5.1"
runner = "1.5.2"
junit = "4.13.2"
junitVersion = "1.1.5"
material = "1.11.0"
media3Exoplayer = "1.3.0"
navigationUiKtx = "2.7.7"
okhttp = "4.9.0"
retrofit = "2.10.0"
roomRuntime = "2.6.1"
uiDesktop = "1.6.3"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
androidx-ui-desktop = { module = "androidx.compose.ui:ui-desktop", version.ref = "uiDesktop" }
material = { module = "com.google.android.material:material", version.ref = "material" }

androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }

dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
junit = { module = "junit:junit", version.ref = "junit" }

navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUiKtx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }

retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }

androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }

reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Detekt
staticAnalysis-detektCli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
staticAnalysis-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
staticAnalysis-detektLibraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }


[bundles]
staticAnalysis-detekt = [
    "staticAnalysis-detektCli",
    "staticAnalysis-detektFormatting",
    "staticAnalysis-detektLibraries"
]

room = [
    "androidx-room-ktx",
    "room-runtime"
]

navigation = [
    "navigation-fragment-ktx",
    "navigation-ui-ktx",
    "fragment-ktx"
]

exoplayer = [
    "androidx-media3-exoplayer",
    "androidx-media3-ui"
]

retrofit2 = [
    "retrofit2-retrofit",
    "converter-gson",
    "okhttp",
    "logging-interceptor"
]

reflect = [
    "reflect"
]


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationUiKtx" }

